{
 "title": "greenplum_dashboard_example",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "The number of tables",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(greenplum_size_table_data)",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "Master",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "greenplum_cluster_coordinator", "legendFormat": "{{coordinator}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "greenplum_cluster_hit_rate", "legendFormat": "Hit rate of cache" },
    {
     "expr": "greenplum_cluster_transition_commit_rate",
     "legendFormat": "Transaction commit rate"
    }
   ]
  },
  {
   "title": "The number of users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "greenplum_user_count" }
   ]
  },
  {
   "title": "Cluster Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "greenplum_connection_total" }
   ]
  },
  {
   "title": "The number of indexes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(greenplum_size_detail_index)",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "Standby",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "greenplum_cluster_standby{standby !=\"\"}",
     "legendFormat": "{{standby}}"
    }
   ]
  },
  {
   "title": "Total client",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "greenplum_connection_total_client_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current client",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "greenplum_user_total_online_count"
    }
   ]
  },
  {
   "title": "Segment status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "greenplum_cluster_segment_status"
    }
   ]
  },
  {
   "title": "Segment mode",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "greenplum_cluster_segment_mode" }
   ]
  },
  {
   "title": "Active connections per client",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "greenplum_connection_active_per_client",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "The disk free size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "greenplum_size_segment_disk_free",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "database lock status",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(greenplum_lock_state{mode=\"AccessShareLock\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(greenplum_lock_state{mode=\"ExclusiveLock\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections per user",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "greenplum_user_active_connection_per",
     "legendFormat": "{{usename}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "greenplum_connection_active", "legendFormat": "active" },
    { "expr": "greenplum_connection_abort", "legendFormat": "abort" },
    { "expr": "greenplum_connection_wait", "legendFormat": "wait" }
   ]
  },
  {
   "title": "Database size (mb)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "greenplum_size_db", "legendFormat": "{{dbname}}" }
   ]
  }
 ]
}